---
name: Default settings for polygon extraction of KITTI dataset
data_folder: "data" # base folder containing KITTI data
date: "2011_09_26" # date of drive
drive: "0018" # drive number, #0093 
cam: 'cam2' # which camera to use, cam0=grey, cam1=grey, cam2=rgb
interactive: true # wait for human key press to proceed to next frame
frames:  # which frames
  # - 0   # start index
  # - 10  # end index
  # - 1   # index jump

# Point Cloud Settings
pointcloud: 
  downsample: 2 # how much to downsample, 1=No downsample, 2 = Every other, N = Every N points
  outlier_removal: true # use simple outlier removal on point cloud
  color: "height" # colorize point cloud by: intensity, height, distance
  color_map: 'plasma'

# 2D/3D View Settings
view_image: # Settings for 2D image viewer
  active: true
  show_pointcloud: false
  show_polygons: true
view_3D: # Settings for 3D point cloud viewer
  active: true
  show_polygons: true
  line_radius: 0.10

# Polygon Extraction Settings
polygon: # Settings for polygons extraction
  polylidar: # Parameters we send to polylidar. Determine plane and polygon extraction from point clouds.
    alpha: 0.0 # must be set to 0.0 if using lmax
    lmax: 1.25 # maximum distance (m) between points in plane for spatial connection
    z_thresh: 0.00 # triangles with z-height (m) less than this have normal filtering skipped. For sensor noise.
    norm_thresh: 0.97 # IGNORE THIS
    norm_thresh_min: 0.97 # minimum level of planarity needed, acos(tri_norm * [0,0,1])
    min_triangles : 3500 # minimum number of triangles in a plane
    min_hole_vertices : 6 # minimum number of vertices in a hole to return
  postprocess: # post processing of polygons returned from polylidar for ground/obstacle identification
    filter: # Filter polygons
      hole_area: # obstacle (holes in polygons) must have these characteristics
        min: 0.5   # m^2
        max: 40 # m^2
      hole_vertices: # obstacles (holes in polygons) must have these characteristics
        min: 3 # A linear ring has a minimum of 3 vertices
      plane_area: # planes must have these area
        min: 30 # m^2
      num_planes_allowed: 1 # TODO Only allow this many largest planes through
    # These parameters correspond to Shapely polygon geometry operations
    positive_buffer: 0.02 # m, Positively expand polygon.  Fills in small holes
    buffer: 0.3 # m, Negative buffer to polygon. Expands holes and constricts outer hull of polygon
    simplify: 0.2  # m, simplify edges of polygon

# Recording Settings
record:
  active: false # do we want to actively record a video
  directory: "data" # what directory to save the mp4
  stacked: true # whether to stack 2D Viewer and 3D Viewer images

# Record Execution Timings to csv file
timings:
  active: false
  directory: "data"
