---
name: Default settings for polygon extraction of KITTI dataset
data_folder: "data" # base folder containing KITTI data
date: "2011_09_26" # date of drive
drive: "0093" # drive number 
frames:  # which frames
  # - 0   # start index
  # - 10  # end index
  # - 1   # index jump
view_image: # Settings for image viewer
  active: true
  cam: '02'
  pointcloud: # project point cloud
    active: true
    color: "intensity" # intensity, height, depth
  polygons:
    active: true
view_3D: # Settings for 3D point cloud viewer
  active: false
polygon: # Settings for polygons extraction
  pointcloud: # Settings for point cloud generation from depth map image
    filter: true
  polylidar: # Parameters we send to polylidar. Determine plane and polygon extracton from point clouds.
    lmax: 0.05 # maximum distance between points in plane for spatial connection
    zThresh: 0.004 # triangles with z-height less than this have normal filtering skipped. For sensor noise.
    normThresh: 0.98 # triangles whose normal is greater than X degrees are filtered acos(tri_norm * [0,0,1])
    alpha: 0.0 # must be set to 0.0 if using lmax
  # ground_normal: # Settings used to estimate normal of ground plane in point cloud.
  #                # This is used to rotate the point cloud such that ground normal aligns with the z-axis
  #   test: 1
  postprocess: # post processing of polygons returned from polylidar for ground/obstacle identification
    filter: # obstacles must have these characteristics
      hole_area:
        min: 75   # cm^2
        max: 7850 # cm^2
      hole_vertices:
        min: 10
      plane_area:
        min: 5000 # cm^2
    buffer: 0.1 # cm, rounded edge buffer
    simplify: 0.5  # cm, simplify edges 
